apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  labels:
  #  {{- include "assessment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
        #{{- include "assessment.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-quotes
          image: busybox:1.36
          command: ['sh', '-c', 'until wget -qO- {{ .Values.api.env.quotesApi }}/api/quote; do echo waiting for quotes; sleep 2; done;']
      containers:
        - name: {{ .Values.api.name }}
          image: {{ .Values.api.image }}
          imagePullPolicy: {{ .Values.api.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: QUOTES_API
              value: {{ .Values.api.env.quotesApi | quote }}
         
