apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.quotes.name }}
  labels:
   # {{- include "assessment.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.quotes.name }}
  ports:
    - port: {{ .Values.quotes.port }}
      targetPort: {{ .Values.quotes.port }}