quotes:
  name: quotes
  image: assessment/quote-service:latest
  imagePullPolicy: Never
  replicaCount: 1
  port: 5000
  probe:
    path: "/api/quote"
    initialDelaySeconds: 5
    periodSeconds: 10

api:
  name: api
  image: assessment/api-gateway:latest
  imagePullPolicy: Never
  replicaCount: 1
  port: 3000
  nodePort: 30300
  env:
    quotesApi: "http://quotes:5000"
  probe:
    path: "/api/status"
    initialDelaySeconds: 5
    periodSeconds: 10


frontend:
  name: frontend
  image: assessment/frontend:latest
  imagePullPolicy: Never
  replicaCount: 1
  port: 80
  nodePort: 30080
  env:
     Api: "http://api:3000"
  probe:
    path: "/"
    initialDelaySeconds: 5
    periodSeconds: 10